version: 2
jobs:
  build:
    docker:
    - image: cimg/node:lts
    steps:
    - run:
        name: Install dependencies
        command: yarn install
    - run:
        name: Run tests
        command: yarn test
