version: 2
jobs:
  build:
    docker:
    - image: cimg/node:lts
    steps:
    - run:
        name: Install dependencies
        command: yarn install
    - run:
        name: Change to the correct directory
        command: cd /Users/masuda_tatsuki/Desktop/CircleCI_Test/
    - run:
        name: Run tests
        command: yarn test
